# -*- coding: utf-8 -*-
"""FAS0_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PLicD1f4OkmHL-t0K-ajcJDi3ov6HIi
"""

from google.colab import drive
import pandas as pd
# Mount Google Drive to access files
drive.mount("/content/drive", force_remount=True)

pip install pypdf langchain

!pip install langchain_text_splitters

import os
from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Path to your PDF folder
DATA_PATH = "/content/drive/MyDrive/ThinkMasters_Capstone/FAS_Kiran_project/data/"

# Step 1: Load all PDFs
def load_pdfs(folder_path):
    documents = []

    for file in os.listdir(folder_path):
        if file.endswith(".pdf"):
            pdf_path = os.path.join(folder_path, file)
            reader = PdfReader(pdf_path)

            text = ""
            for page in reader.pages:
                text += page.extract_text() or ""

            documents.append({
                "text": text,
                "source": file
            })

    return documents


!pip install nltk
import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

def semantic_chunking(text, chunk_size=500):
    sentences = sent_tokenize(text)

    chunks = []
    current_chunk = ""

    for sentence in sentences:

        # If sentence fits in current chunk
        if len(current_chunk) + len(sentence) <= chunk_size:
            current_chunk += " " + sentence

        else:
            # Save current chunk
            chunks.append(current_chunk.strip())

            # Start new chunk
            current_chunk = sentence

    # Add last chunk
    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

# Split into chunks
def split_text(documents):

    chunks = []

    for doc in documents:

        # Semantic chunking
        split_chunks = semantic_chunking(doc["text"])

        for chunk in split_chunks:
            chunks.append({
                "text": chunk,
                "source": doc["source"]
            })

    return chunks


# Run pipeline
if __name__ == "__main__":
    print("Loading PDFs...")
    docs = load_pdfs(DATA_PATH)

    print(f"Loaded {len(docs)} documents")

    print("Splitting into chunks...")
    chunks = split_text(docs)

    print(f"Total chunks created: {len(chunks)}")

# Fixed sample print to access dictionary keys
    print("\n--- Sample Chunk Output ---")
    if chunks:
        print(f"Source File: {chunks[2005]['source']}")
        print(f"Chunk Content: {chunks[2005]['text'][:500]}...")

import re

def clean_text(text):

    # Preserve paragraph structure
    text = re.sub(r'[ \t]+', ' ', text)

    # Normalize newlines
    text = re.sub(r'\n+', '\n', text)

    # Remove garbage artifacts
    text = re.sub(r'\byy\b', '', text)

    # Remove unicode bullets
    text = re.sub(r'[•▪◦]', '', text)

    # Remove standalone page numbers
    text = re.sub(r'\n\d+\n', '\n', text)

    # Remove URLs
    text = re.sub(r'www\.\S+', '', text)
    text = re.sub(r'http\S+', '', text)

    return text.strip()

cleaned_chunks = [clean_text(chunk["text"]) for chunk in chunks]

  # Print sample minimal cleaned chunks
print("\nSample cleaned chunk:\n")
print(cleaned_chunks[0][:500])

# Fix: Re-run the cleaning while preserving the dictionary structure
# This ensures each item has both 'text' and 'source'
cleaned_chunks = [
    {
        "text": clean_text(chunk["text"]),
        "source": chunk["source"]
    }
    for chunk in chunks
]

print("\n--- Sample Chunk Output ---")
if cleaned_chunks:
    print(f"Source File: {cleaned_chunks[0]['source']}")
    print(f"Chunk Content: {cleaned_chunks[0]['text'][:500]}...")

!pip install sentence-transformers faiss-cpu numpy

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pickle

# Your cleaned chunks are a list of dictionaries
# we need to extract the text strings for the model

print("Loading embedding model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

print("Creating embeddings...")
# Fix: Extract 'text' from each dictionary in the list
chunk_texts = [chunk["text"] for chunk in cleaned_chunks]
embeddings = model.encode(chunk_texts, show_progress_bar=True)

# Convert to float32 (required by FAISS)
embeddings = np.array(embeddings).astype("float32")

# Create FAISS index
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)

# Add embeddings
index.add(embeddings)

print(f"Stored {index.ntotal} vectors in FAISS")

# Save index
faiss.write_index(index, "faiss_index.bin")

# Save chunks (VERY IMPORTANT)
with open("chunks.pkl", "wb") as f:
    pickle.dump(cleaned_chunks, f)

print("✅ FAISS index + chunks saved successfully")

from sentence_transformers import SentenceTransformer
import faiss
import pickle
import numpy as np

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Load FAISS index
index = faiss.read_index("faiss_index.bin")

# Load chunks
with open("chunks.pkl", "rb") as f:
    chunks = pickle.load(f)

# Test query
query = "sugarcane"

# Convert query to embedding
query_embedding = model.encode([query]).astype("float32")

# Search
k = 3
distances, indices = index.search(query_embedding, k)

print("\n🔍 Top Results:\n")

for i in indices[0]:
    chunk = chunks[i]
    print(f"Source: {chunk['source']}")
    print(f"Text: {chunk['text']}")
    print("-" * 60)

!pip install rank_bm25

from rank_bm25 import BM25Okapi
import pickle

# Load your chunks (already saved)
with open("chunks.pkl", "rb") as f:
    chunks = pickle.load(f)

# Step 1: Tokenize text
def tokenize(text):
    return text.lower().split()

# Fix: Pass the 'text' value from the dictionary to the tokenizer
tokenized_chunks = [tokenize(chunk["text"]) for chunk in chunks]

# Step 2: Create BM25 model
bm25 = BM25Okapi(tokenized_chunks)

# Save BM25 model
with open("bm25.pkl", "wb") as f:
    pickle.dump(bm25, f)

print("✅ BM25 index created and saved")

import pickle

# Load BM25 model
with open("bm25.pkl", "rb") as f:
    bm25 = pickle.load(f)

# Load chunks
with open("chunks.pkl", "rb") as f:
    chunks = pickle.load(f)

# Query
query = "sugarcane"

# Tokenize query
tokenized_query = query.lower().split()

# Get scores
scores = bm25.get_scores(tokenized_query)

# Get top k results
k = 5
top_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]

print("\n🔍 BM25 Top Results:\n")

for i in top_indices:
    chunk = chunks[i]
    print(f"Source: {chunk['source']}")
    print(f"Text: {chunk['text']}")
    print("-" * 60)

from sentence_transformers import SentenceTransformer
import faiss
import pickle
import numpy as np

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Load FAISS
index = faiss.read_index("faiss_index.bin")

# Load chunks
with open("chunks.pkl", "rb") as f:
    chunks = pickle.load(f)

# Load BM25
with open("bm25.pkl", "rb") as f:
    bm25 = pickle.load(f)

def hybrid_search(query, k=5, alpha=0.5):
    tokenized_query = query.lower().split()
    bm25_scores = bm25.get_scores(tokenized_query)

    query_embedding = model.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, len(chunks))

    embedding_scores = np.zeros(len(chunks))
    for rank, idx in enumerate(indices[0]):
        embedding_scores[idx] = 1 / (1 + distances[0][rank])

    # Normalize
    bm25_scores = np.array(bm25_scores)
    if bm25_scores.max() != 0:
        bm25_scores = bm25_scores / bm25_scores.max()

    if embedding_scores.max() != 0:
        embedding_scores = embedding_scores / embedding_scores.max()

    #final_scores = alpha * bm25_scores + (1 - alpha) * embedding_scores

    # Rank fusion
    bm25_rank = np.argsort(np.argsort(-bm25_scores))
    embedding_rank = np.argsort(np.argsort(-embedding_scores))

    # Combine ranks
    final_scores = -(bm25_rank + embedding_rank)

    # Sort all results
    sorted_indices = np.argsort(final_scores)[::-1]

    # Remove duplicates based on normalized prefix (first 100 chars)
    # This catches near-duplicates and overlapping chunks
    seen_prefixes = set()
    results = []

    for i in sorted_indices:
        chunk = chunks[i]
        # Normalize and take a prefix for similarity checking
        normalized_text  = " ".join(chunk['text'].split()).lower()
        prefix = normalized_text[:100]

        if prefix not in seen_prefixes:
            results.append((i, chunk, final_scores[i]))
            seen_prefixes.add(prefix)

        if len(results) == k:
            break

    return results

query = "varieties sugarcane"

results = hybrid_search(query, k=9, alpha=0.2)

print("\n🔍 Hybrid Search Results:\n")

for idx, chunk, score in results:
    # Correctly accessing and printing both source and text for every chunk
    print(f"Source: {chunk['source']}")
    print(f"Score: {score:.4f}")
    print(f"Text: {chunk['text']}")
    print("-" * 60)

!pip install openai

import os

from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


def generate_answer(query, retrieved_chunks):
    context = "\n\n".join(retrieved_chunks[:3])  # keep top 3 chunks

    prompt = f"""
You are an agriculture expert assistant.

Answer the question ONLY using the provided context.

Format your answer clearly:
- Use bullet points where possible
- Keep sentences short
- Add line breaks for readability

If the answer is not in the context, say "I don't know".

Context:
{context}

Question:
{query}

Answer:
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",   # fast + cheap + good
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

query = "What are the varieties of sugarcane?"

results = hybrid_search(query, k=3)

retrieved_chunks = [item["text"] for _, item, _ in results]

answer = generate_answer(query, retrieved_chunks)

print("\n🧠 Answer:\n")
print(answer)

print("\n📄 Sources Used:\n")

for i, item, score in results:
    print(f"📄 Document: {item['source']} | Score: {score:.4f}")
    print(item["text"][:500])
    print("-" * 60)

def bm25_search(query, k=3):

    tokenized_query = tokenize(query)

    scores = bm25.get_scores(tokenized_query)

    top_indices = np.argsort(scores)[::-1][:k]

    results = []

    for i in top_indices:

        results.append((i, chunks[i], scores[i]))

    return results


def embedding_search(query, k=3):

    query_embedding = model.encode([query]).astype("float32")

    distances, indices = index.search(query_embedding, k)

    results = []

    for rank, idx in enumerate(indices[0]):

        score = 1 / (1 + distances[0][rank])

        results.append((idx, chunks[idx], score))

    return results


evaluation_queries = [

    "Which crop is suitable for monsoon season?",

    "What are the varieties of sugarcane?",

    "How to control rice leaf folder pest?",

    "What is the shelf life of Beauveria bassiana formulation?",

    "Which soil is suitable for wheat cultivation?",

    "How to manage pest attacks in cotton?",

    "What are the biofertilizers used in agriculture?",

    "What irrigation is required for wheat?",

    "How to increase rice productivity?",

    "What are common rice diseases?"
]

def run_rag(method_func, query):

    # Retrieve more chunks
    results = method_func(query, k=9)

    # Send only top 3 chunks to LLM
    retrieved_chunks = [
        item["text"]
        for idx, item, score in results[:3]
    ]

    # Generate answer
    answer = generate_answer(query, retrieved_chunks)

    return answer, results


def evaluate_query(query):

    methods = {
        "BM25": bm25_search,
        "Embedding": embedding_search,
        "Hybrid": hybrid_search
    }

    print("\n" + "="*120)
    print(f"QUERY: {query}")
    print("="*120)

    for method_name, method_func in methods.items():

        print(f"\n🔍 METHOD: {method_name}")
        print("-"*120)

        # Use common pipeline
        answer, results = run_rag(method_func, query)

        # Show top 3 retrieved chunks
        print("\n📄 RETRIEVED CHUNKS:\n")

        for idx, item, score in results[:3]:

            print(f"📄 Source: {item['source']}")
            print(f"📊 Score: {score:.4f}")

            print(item["text"][:500])

            print("-"*80)

        # Show answer
        print("\n🧠 GENERATED ANSWER:\n")

        print(answer)

        print("\n" + "#"*120)




for query in evaluation_queries:

    evaluate_query(query)

"""🏁 FINAL TECHNICAL CONCLUSION
🥇 Best Semantic Retrieval
Embedding Retrieval

gave:

the most relevant chunks
the most accurate answers
the strongest semantic understanding

for agriculture-related natural language queries.

🥈 Best Practical Real-World System
Hybrid Retrieval

provided:

balanced retrieval
robustness across query types
improved generalization

making it more suitable for:

real-world farmer advisory deployments.
🥉 Weakest Semantic Method
BM25

performed poorly for:

natural language queries
semantic understanding
contextual agricultural retrieval

due to strict keyword dependence.



## Embedding-based retrieval achieved the best semantic relevance and answer quality for agriculture advisory queries. Hybrid retrieval provided more balanced and robust performance across diverse real-world query types, while BM25 was effective only for exact keyword matching and struggled with semantic understanding.




"""

from google.colab import files

files.download("faiss_index.bin")
files.download("chunks.pkl")
files.download("bm25.pkl")